<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="TermsOfUse.aspx.cs" Inherits="TermsOfUse" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div align="center">
    <h3 style="box-sizing: border-box; font-family: Arial, Helvetica, sans-serif; font-weight: bold; line-height: 1.1; color: rgb(51, 51, 51); margin-top: 24px; margin-bottom: 12px; font-size: 17px; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <asp:Label ID="Label1" runat="server" Text="General" Font-Bold="True" Font-Size="Medium" ForeColor="Red"></asp:Label>
        </h3>
    <p style="box-sizing: border-box; margin: 0px 0px 12px; color: rgb(102, 102, 102); font-family: 'Trebuchet MS', Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        NHS Blood and Transplant (NHSBT) is a Special Health Authority within the NHS, responsible for managing NHS Blood and Transplant.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 12px; color: rgb(102, 102, 102); font-family: 'Trebuchet MS', Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        This website (excluding linked sites) is controlled by NHS Blood and Transplant. The site can be accessed from countries around the World. As each of these places has laws that may differ from those of England by accessing the site both you and we agree that the laws of England shall apply to all matters arising from or relating to the use and contents of this site. You also agree and hereby submit to the non-exclusive jurisdiction of the courts of England with respect to such matters.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 12px; color: rgb(102, 102, 102); font-family: 'Trebuchet MS', Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        By accessing and using this website in any way, including, without limitation, browsing the website, registering as a donor, using any information, using any content, using any services, downloading any materials, you agree to and are bound by these Legal Notices. If you do not accept these Legal Notices in full, please cease using this website immediately.</p>
        <asp:Label ID="Label2" runat="server" Text="Terms of Use for Users of the Online Blood Donor Register" Font-Bold="True" Font-Size="Medium" ForeColor="Red"></asp:Label>
    <p style="box-sizing: border-box; margin: 0px 0px 12px; color: rgb(102, 102, 102); font-family: 'Trebuchet MS', Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        The terms of use and privacy policy for the NHS Blood &amp; Transplant website govern your use of NHS Blood &amp; Transplant Online Blood Donor Register. In addition, the following terms apply:</p>
    <p style="box-sizing: border-box; margin: 0px 0px 12px; color: rgb(102, 102, 102); font-family: 'Trebuchet MS', Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        We may amend these terms of use from time to time, and the revised version will be effective when displayed here.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 12px; color: rgb(102, 102, 102); font-family: 'Trebuchet MS', Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        Although we have taken precautions, you should note that the Internet is not a secure medium, and any information sent through the Online Blood Donor Register may be intercepted and may not arrive safely at its ultimate destination.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 12px; color: rgb(102, 102, 102); font-family: 'Trebuchet MS', Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        If accessing any part of the Online Blood Donor Register that requires you to enter a password you agree:</p>
    <p style="box-sizing: border-box; margin: 0px 0px 12px; color: rgb(102, 102, 102); font-family: 'Trebuchet MS', Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        To ensure that any details which you supply to us to register for such access are accurate and to update your profile promptly if any of the details which you have supplied to us about you change;</p>
    <p style="box-sizing: border-box; margin: 0px 0px 12px; color: rgb(102, 102, 102); font-family: 'Trebuchet MS', Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        To keep any personal login name and any password confidential, and to be responsible for any loss or damage resulting from use of your password by any third party;</p>
    <p style="box-sizing: border-box; margin: 0px 0px 12px; color: rgb(102, 102, 102); font-family: 'Trebuchet MS', Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        That we reserve the right to terminate your access to the Online Blood Donor Register should we consider that your use of the register is detrimental to the Online Blood Donor Register or to other users.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 12px; color: rgb(102, 102, 102); font-family: 'Trebuchet MS', Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        We shall use any personal information you submit to the Online Blood Donor Register and other information we hold about you in accordance with our privacy policy. In particular, we shall use the information (including sensitive personal information relating to your physical health) to provide you with a blood donor information service as described. By registering for the service through this form, you give your consent to such use of your personal information.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 12px; color: rgb(102, 102, 102); font-family: 'Trebuchet MS', Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        While we will use our reasonable endeavours to ensure that the information provided by the Online Blood Register is accurate, the register (including records of blood stocks, your blood type and quantities of blood donated) is provided to support your own records and you should always check with an appropriately qualified health professional before donating blood.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 12px; color: rgb(102, 102, 102); font-family: 'Trebuchet MS', Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        By registering online as a blood donor, you agree to the NHS Blood &amp; Transplant&#39;s general terms of use (including disclaimers), privacy policy and these terms of use.</p>
</div>
</asp:Content> 

